# Generated by Django 3.1.6 on 2021-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210217_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_obesity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
