# Generated by Django 3.1.6 on 2021-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210217_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_url',
            field=models.URLField(max_length=2000),
        ),
    ]
