# Generated by Django 3.1.6 on 2021-02-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210217_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activity_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.activitylevel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.agelevel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.gendercode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegan_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.veganlevel'),
        ),
    ]
