# Generated by Django 3.1.6 on 2021-02-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210217_0932'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productallergy',
            table='product_allergies',
        ),
    ]
