# Generated by Django 3.1.6 on 2021-02-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210218_0521'),
        ('product', '0006_auto_20210218_0252'),
    ]

    operations = [
    ]
