# Generated by Django 3.1.6 on 2021-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210222_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='goal',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
