# Generated by Django 3.1.6 on 2021-02-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('quiz', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='user',
            name='recommendation',
            field=models.ManyToManyField(through='quiz.QuizResult', to='product.Product'),
        ),
    ]
