# Generated by Django 3.1.6 on 2021-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipStatus',
            new_name='ShipmentStatus',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ship_status',
            new_name='shipment_status',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='shipmentstatus',
            table='shipment_status',
        ),
    ]
