# Generated by Django 3.1.6 on 2021-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_merge_20210219_0629'),
        ('order', '0004_auto_20210217_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_stock',
            field=models.ManyToManyField(through='order.OrderProductStock', to='product.ProductStock'),
        ),
    ]
