# Generated by Django 3.1.6 on 2021-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
