# Generated by Django 3.1.6 on 2021-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210222_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=1111, max_length=1000),
            preserve_default=False,
        ),
    ]
